// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5DgmFwL_8DsQ36ZR5--yKRTQrrz9P7Lk',
    appId: '1:705080367622:web:a6c1463a556831c3058187',
    messagingSenderId: '705080367622',
    projectId: 'smarttransitzw',
    authDomain: 'smarttransitzw.firebaseapp.com',
    storageBucket: 'smarttransitzw.firebasestorage.app',
    measurementId: 'G-Z6QMPKF3KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFzJ6uXnFGrcsgW4RwQ5f7qd5wen8RU-E',
    appId: '1:705080367622:android:c32c59488082a2a3058187',
    messagingSenderId: '705080367622',
    projectId: 'smarttransitzw',
    storageBucket: 'smarttransitzw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_kxxFWrL__8lEKxHFAq4VkBniTeoOYU',
    appId: '1:705080367622:ios:2d0293038edf9b94058187',
    messagingSenderId: '705080367622',
    projectId: 'smarttransitzw',
    storageBucket: 'smarttransitzw.firebasestorage.app',
    iosBundleId: 'com.example.smarttransitzw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7_kxxFWrL__8lEKxHFAq4VkBniTeoOYU',
    appId: '1:705080367622:ios:2d0293038edf9b94058187',
    messagingSenderId: '705080367622',
    projectId: 'smarttransitzw',
    storageBucket: 'smarttransitzw.firebasestorage.app',
    iosBundleId: 'com.example.smarttransitzw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5DgmFwL_8DsQ36ZR5--yKRTQrrz9P7Lk',
    appId: '1:705080367622:web:153d175a26f283d8058187',
    messagingSenderId: '705080367622',
    projectId: 'smarttransitzw',
    authDomain: 'smarttransitzw.firebaseapp.com',
    storageBucket: 'smarttransitzw.firebasestorage.app',
    measurementId: 'G-SPJSZRYSTB',
  );
}
